-- let x = ((1, 'a'), True)
-- (a) the type of x by a GHCi command 
--     x :: ((Integer, Char), Bool)
-- (b) How do you extract the 1 in x?
--     fst (fst x)
-- (c) extract 'a' from x
--     snd (fst x)
-- (d) extract True from x
--     snd x
